service: line-bot-example

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: seapolis-admin

package:
  exclude:
    - .git/**

functions:
  app:
    handler: dist/handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'